-- ============================================================================
-- Orçamento do Atacado (plano de precificação v3) — DDL PostgreSQL
-- Aplicar MANUALMENTE (não usar prisma migrate). Idempotente.
--
-- O ERP (Celta/Firebird) continua a fonte da verdade de cadastro, saldo e
-- tabela de preço; o BI, a fonte da venda realizada. O que mora aqui é o que
-- o ERP não tem:
--   ven_regua_atacado        -> a régua v3: classe (GERAL | PB) × faixa (1A..3D)
--                                = markup de lista + desconto máximo do vendedor.
--   ven_regua_item_excecao   -> itens fora da régua (LANÇAMENTO/EXCLUSIVO e
--                                COMPRA DE OPORTUNIDADE): markup atual congelado,
--                                desconto máximo próprio. Revisão mensal.
--   ven_orcamento            -> o orçamento feito NA INTRANET (cabeçalho).
--   ven_orcamento_item       -> os itens, com a fotografia da régua no momento
--                                (classe, faixa, desc. máx, preço mínimo, custo).
--   ven_produto_relacionado  -> "vendem juntos": pares apurados no BI (12 meses
--                                do atacado), recalculados por cron semanal.
-- ============================================================================

-- 1) Régua v3 -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ven_regua_atacado (
  id          SERIAL PRIMARY KEY,
  classe      TEXT NOT NULL,                       -- GERAL | PB
  faixa       TEXT NOT NULL,                       -- 1A 1B 1C 1D 2A 2B 2C 3A 3B 3C 3D
  markup      NUMERIC(6,3) NOT NULL,               -- preço de lista = custo × markup
  desc_max    NUMERIC(5,4) NOT NULL,               -- desconto máximo do vendedor (0.03 = 3%)
  ativo       BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_ven_regua_atacado UNIQUE (classe, faixa)
);

-- Seed = régua v3 aprovada (ago/2026). ON CONFLICT mantém o que já estiver ajustado.
INSERT INTO ven_regua_atacado (classe, faixa, markup, desc_max) VALUES
  ('GERAL','1A',2.850,0.03),('GERAL','1B',2.300,0.03),('GERAL','1C',1.950,0.03),('GERAL','1D',1.850,0.03),
  ('GERAL','2A',1.700,0.05),('GERAL','2B',1.620,0.06),('GERAL','2C',1.560,0.07),
  ('GERAL','3A',1.510,0.08),('GERAL','3B',1.470,0.08),('GERAL','3C',1.440,0.09),('GERAL','3D',1.420,0.10),
  ('PB','1A',2.300,0.03),('PB','1B',2.100,0.03),('PB','1C',1.900,0.03),('PB','1D',1.750,0.03),
  ('PB','2A',1.600,0.05),('PB','2B',1.500,0.06),('PB','2C',1.440,0.07),
  ('PB','3A',1.420,0.08),('PB','3B',1.410,0.08),('PB','3C',1.390,0.09),('PB','3D',1.380,0.10)
ON CONFLICT (classe, faixa) DO NOTHING;

-- 1b) Escala por VOLUME (quantidade na linha) ----------------------------------
-- O desconto máximo da FAIXA é o teto e nunca cresce. A quantidade decide que
-- fração desse máximo o vendedor pode dar sozinho: 50% até 2 un, 75% de 3 a 5,
-- 100% a partir de 6. Tabela recriada aqui porque a 1ª versão (adicional em p.p.)
-- passava do máximo da faixa — o que o plano não permite.
DROP TABLE IF EXISTS ven_regua_volume;
CREATE TABLE ven_regua_volume (
  id         SERIAL PRIMARY KEY,
  qtd_min    INTEGER NOT NULL UNIQUE,
  fracao     NUMERIC(5,4) NOT NULL CHECK (fracao > 0 AND fracao <= 1),
  ativo      BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO ven_regua_volume (qtd_min, fracao) VALUES (1, 0.50), (3, 0.75), (6, 1.00);

-- 2) Exceções da régua (lançamento/exclusivo e oportunidade) -------------------
CREATE TABLE IF NOT EXISTS ven_regua_item_excecao (
  pro_codigo   INTEGER PRIMARY KEY,
  classe       TEXT NOT NULL,                      -- EXCLUSIVO | OPORTUNIDADE
  desc_max     NUMERIC(5,4),                       -- NULL = usa o desc. máx da faixa do item
  motivo       TEXT,
  vigente_ate  DATE,                               -- NULL = sem prazo; revisão mensal no painel
  criado_por   TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3) Orçamento (cabeçalho) ------------------------------------------------------
CREATE TABLE IF NOT EXISTS ven_orcamento (
  id                 TEXT PRIMARY KEY,
  numero             INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,  -- ORC-000123
  empresa            INTEGER NOT NULL DEFAULT 3,
  cli_codigo         INTEGER NOT NULL,
  cli_nome           TEXT,
  tabela_preco       TEXT,                         -- cópia de CLIENTES.TABELA_PRECO na emissão
  rep_codigo         INTEGER,
  rep_nome           TEXT,
  status             TEXT NOT NULL DEFAULT 'RASCUNHO', -- RASCUNHO | ENVIADO | APROVACAO | FECHADO | PERDIDO | CANCELADO
  validade           DATE,
  observacao         TEXT,
  subtotal           NUMERIC(15,2) NOT NULL DEFAULT 0, -- Σ qtd × preço de tabela
  desconto_total     NUMERIC(15,2) NOT NULL DEFAULT 0,
  total              NUMERIC(15,2) NOT NULL DEFAULT 0,
  desc_pct           NUMERIC(6,4)  NOT NULL DEFAULT 0, -- desconto_total / subtotal
  acima_alcada       BOOLEAN NOT NULL DEFAULT FALSE,   -- algum item abaixo do preço mínimo
  bolsa_pct_antes    NUMERIC(6,4),                     -- % de desconto do vendedor no mês, antes
  bolsa_pct_depois   NUMERIC(6,4),                     -- ... e se este orçamento fechar
  aprovado_por       TEXT,
  aprovado_em        TIMESTAMPTZ,
  enviado_em         TIMESTAMPTZ,
  desfecho_em        TIMESTAMPTZ,
  desfecho_motivo    TEXT,                             -- PERDIDO: PRECO | PRAZO_FRETE | SEM_ESTOQUE | CONCORRENTE | CLIENTE_ADIOU | CREDITO_BLOQUEADO
  desfecho_ref       TEXT,                             -- FECHADO: nº do pedido/NF no Celta
  usuario_id         TEXT,
  usuario_nome       TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ven_orcamento_rep_status ON ven_orcamento (rep_codigo, status);
CREATE INDEX IF NOT EXISTS idx_ven_orcamento_cli        ON ven_orcamento (cli_codigo);
CREATE INDEX IF NOT EXISTS idx_ven_orcamento_created    ON ven_orcamento (created_at);

-- 4) Itens do orçamento ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS ven_orcamento_item (
  id                 TEXT PRIMARY KEY,
  orcamento_id       TEXT NOT NULL REFERENCES ven_orcamento(id) ON DELETE CASCADE,
  item               INTEGER NOT NULL,
  pro_codigo         INTEGER NOT NULL,
  descricao          TEXT,
  referencia         TEXT,
  unidade            TEXT,
  quantidade         NUMERIC(15,3) NOT NULL DEFAULT 1,
  preco_tabela       NUMERIC(15,2) NOT NULL,        -- preço da tabela do cliente no ERP
  tabela_coluna      TEXT,                          -- PRECO2 | PRECO5 | ... | PRECO_VENDA
  preco_unit         NUMERIC(15,2) NOT NULL,        -- preço negociado
  desc_pct           NUMERIC(6,4)  NOT NULL DEFAULT 0,
  total              NUMERIC(15,2) NOT NULL,
  custo_ref          NUMERIC(15,2),                 -- PRECO_CUSTO (reposição) no momento
  classe             TEXT,                          -- GERAL | PB | EXCLUSIVO | OPORTUNIDADE
  mix                INTEGER,
  faixa              TEXT,                          -- 1A..3D
  markup_regua       NUMERIC(6,3),
  desc_max_pct       NUMERIC(6,4),
  preco_minimo       NUMERIC(15,2),
  acima_alcada       BOOLEAN NOT NULL DEFAULT FALSE,
  estoque_disponivel NUMERIC(15,3),                 -- fotografia do saldo na hora
  substituto_de      INTEGER,                       -- pro_codigo sem saldo que este item substitui
  observacao         TEXT
);
-- Item em promoção vigente na tabela do cliente (preço fechado; define a validade).
ALTER TABLE ven_orcamento_item ADD COLUMN IF NOT EXISTS promocao_codigo INTEGER;
ALTER TABLE ven_orcamento_item ADD COLUMN IF NOT EXISTS promocao_fim    DATE;
CREATE INDEX IF NOT EXISTS idx_ven_orcamento_item_orc ON ven_orcamento_item (orcamento_id);
CREATE INDEX IF NOT EXISTS idx_ven_orcamento_item_pro ON ven_orcamento_item (pro_codigo);

-- 5) Vendem juntos (apuração semanal no BI) -------------------------------------
CREATE TABLE IF NOT EXISTS ven_produto_relacionado (
  pro_codigo       INTEGER NOT NULL,
  pro_relacionado  INTEGER NOT NULL,
  juntos           INTEGER NOT NULL,                -- notas em que os dois saíram juntos
  base             INTEGER NOT NULL,                -- notas em que pro_codigo saiu
  suporte_pct      NUMERIC(6,4) NOT NULL,           -- juntos / base
  calculado_em     TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (pro_codigo, pro_relacionado)
);

-- 6) Permissão da tela (módulo Vendas é ESTRITO: cada tela liberada por usuário).
-- Exemplo — ajuste os usuários:
-- INSERT INTO sis_permissoes (id, usuario_id, modulo, tela, visualizar, editar, criar, deletar)
-- SELECT gen_random_uuid()::text, u.id, 'Vendas', '/vendas/orcamento', true, true, true, false
-- FROM sis_usuarios u WHERE u.codigo IN ('<codigo>') AND NOT EXISTS (
--   SELECT 1 FROM sis_permissoes p WHERE p.usuario_id = u.id AND p.tela = '/vendas/orcamento');
