-- ============================================================================
-- Orçamento do Atacado (plano de precificação v3) — DDL PostgreSQL
-- Aplicar MANUALMENTE (não usar prisma migrate). Idempotente.
--
-- O ERP (Celta/Firebird) continua a fonte da verdade de cadastro, saldo e
-- tabela de preço; o BI, a fonte da venda realizada. O que mora aqui é o que
-- o ERP não tem:
--   ven_regua_atacado        -> a régua v3: classe (GERAL | PB) × faixa (1A..3D)
--                                = markup de lista + desconto máximo do vendedor.
--   ven_regua_item_excecao   -> itens fora da régua (LANÇAMENTO/EXCLUSIVO e
--                                COMPRA DE OPORTUNIDADE): markup atual congelado,
--                                desconto máximo próprio. Revisão mensal.
--   ven_orcamento            -> o orçamento feito NA INTRANET (cabeçalho).
--   ven_orcamento_item       -> os itens, com a fotografia da régua no momento
--                                (classe, faixa, desc. máx, preço mínimo, custo).
--   ven_produto_relacionado  -> "vendem juntos": pares apurados no BI (12 meses
--                                do atacado), recalculados por cron semanal.
-- ============================================================================

-- 1) Régua v3 -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ven_regua_atacado (
  id          SERIAL PRIMARY KEY,
  classe      TEXT NOT NULL,                       -- GERAL | PB
  faixa       TEXT NOT NULL,                       -- 1A 1B 1C 1D 2A 2B 2C 3A 3B 3C 3D
  markup      NUMERIC(6,3) NOT NULL,               -- preço de lista = custo × markup
  desc_max    NUMERIC(5,4) NOT NULL,               -- desconto máximo do vendedor (0.03 = 3%)
  ativo       BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_ven_regua_atacado UNIQUE (classe, faixa)
);

-- Seed = régua vigente (v3 ago/2026 + ajustes da diretoria 09/09/2026: faixas caras no piso
-- 1,538 com limites maiores; mix 1 com 5% sobre lista ~2,1% mais alta — ver
-- regua_mix1_5pct_postgres.sql). ON CONFLICT mantém o que já estiver ajustado.
INSERT INTO ven_regua_atacado (classe, faixa, markup, desc_max) VALUES
  ('GERAL','1A',2.910,0.05),('GERAL','1B',2.350,0.05),('GERAL','1C',1.990,0.05),('GERAL','1D',1.890,0.05),
  ('GERAL','2A',1.700,0.05),('GERAL','2B',1.620,0.06),('GERAL','2C',1.560,0.07),('GERAL','3A',1.538,0.10),
  ('GERAL','3B',1.538,0.12),('GERAL','3C',1.538,0.15),('GERAL','3D',1.538,0.17),('PB','1A',2.350,0.05),
  ('PB','1B',2.140,0.05),('PB','1C',1.940,0.05),('PB','1D',1.790,0.05),('PB','2A',1.600,0.05),
  ('PB','2B',1.538,0.08),('PB','2C',1.538,0.13),('PB','3A',1.538,0.15),('PB','3B',1.538,0.16),
  ('PB','3C',1.538,0.18),('PB','3D',1.538,0.19)
ON CONFLICT (classe, faixa) DO NOTHING;

-- 1b) Escala por VOLUME (quantidade na linha) ----------------------------------
-- O desconto máximo da FAIXA é o teto e nunca cresce. A quantidade decide que
-- fração desse máximo o vendedor pode dar sozinho: 50% até 2 un, 75% de 3 a 5,
-- 100% a partir de 6. Tabela recriada aqui porque a 1ª versão (adicional em p.p.)
-- passava do máximo da faixa — o que o plano não permite.
DROP TABLE IF EXISTS ven_regua_volume;
CREATE TABLE ven_regua_volume (
  id         SERIAL PRIMARY KEY,
  qtd_min    INTEGER NOT NULL UNIQUE,
  fracao     NUMERIC(5,4) NOT NULL CHECK (fracao > 0 AND fracao <= 1),
  ativo      BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO ven_regua_volume (qtd_min, fracao) VALUES (1, 0.50), (3, 0.75), (6, 1.00);

-- 2) Exceções da régua (lançamento/exclusivo e oportunidade) -------------------
CREATE TABLE IF NOT EXISTS ven_regua_item_excecao (
  pro_codigo   INTEGER PRIMARY KEY,
  classe       TEXT NOT NULL,                      -- EXCLUSIVO | OPORTUNIDADE
  desc_max     NUMERIC(5,4),                       -- NULL = usa o desc. máx da faixa do item
  motivo       TEXT,
  vigente_ate  DATE,                               -- NULL = sem prazo; revisão mensal no painel
  criado_por   TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3) Orçamento (cabeçalho) ------------------------------------------------------
CREATE TABLE IF NOT EXISTS ven_orcamento (
  id                 TEXT PRIMARY KEY,
  numero             INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,  -- ORC-000123
  empresa            INTEGER NOT NULL DEFAULT 3,
  cli_codigo         INTEGER NOT NULL,
  cli_nome           TEXT,
  tabela_preco       TEXT,                         -- cópia de CLIENTES.TABELA_PRECO na emissão
  rep_codigo         INTEGER,
  rep_nome           TEXT,
  status             TEXT NOT NULL DEFAULT 'RASCUNHO', -- RASCUNHO | ENVIADO | APROVACAO | FECHADO | PERDIDO | CANCELADO
  validade           DATE,
  observacao         TEXT,
  subtotal           NUMERIC(15,2) NOT NULL DEFAULT 0, -- Σ qtd × preço de tabela
  desconto_total     NUMERIC(15,2) NOT NULL DEFAULT 0,
  total              NUMERIC(15,2) NOT NULL DEFAULT 0,
  desc_pct           NUMERIC(6,4)  NOT NULL DEFAULT 0, -- desconto_total / subtotal
  acima_alcada       BOOLEAN NOT NULL DEFAULT FALSE,   -- algum item abaixo do preço mínimo
  bolsa_pct_antes    NUMERIC(6,4),                     -- % de desconto do vendedor no mês, antes
  bolsa_pct_depois   NUMERIC(6,4),                     -- ... e se este orçamento fechar
  aprovado_por       TEXT,
  aprovado_em        TIMESTAMPTZ,
  enviado_em         TIMESTAMPTZ,
  desfecho_em        TIMESTAMPTZ,
  desfecho_motivo    TEXT,                             -- PERDIDO: PRECO | PRAZO_FRETE | SEM_ESTOQUE | CONCORRENTE | CLIENTE_ADIOU | CREDITO_BLOQUEADO
  desfecho_ref       TEXT,                             -- FECHADO: nº do pedido/NF no Celta
  usuario_id         TEXT,
  usuario_nome       TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ven_orcamento_rep_status ON ven_orcamento (rep_codigo, status);
CREATE INDEX IF NOT EXISTS idx_ven_orcamento_cli        ON ven_orcamento (cli_codigo);
CREATE INDEX IF NOT EXISTS idx_ven_orcamento_created    ON ven_orcamento (created_at);

-- 4) Itens do orçamento ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS ven_orcamento_item (
  id                 TEXT PRIMARY KEY,
  orcamento_id       TEXT NOT NULL REFERENCES ven_orcamento(id) ON DELETE CASCADE,
  item               INTEGER NOT NULL,
  pro_codigo         INTEGER NOT NULL,
  descricao          TEXT,
  referencia         TEXT,
  unidade            TEXT,
  quantidade         NUMERIC(15,3) NOT NULL DEFAULT 1,
  preco_tabela       NUMERIC(15,2) NOT NULL,        -- preço da tabela do cliente no ERP
  tabela_coluna      TEXT,                          -- PRECO2 | PRECO5 | ... | PRECO_VENDA
  preco_unit         NUMERIC(15,2) NOT NULL,        -- preço negociado
  desc_pct           NUMERIC(6,4)  NOT NULL DEFAULT 0,
  total              NUMERIC(15,2) NOT NULL,
  custo_ref          NUMERIC(15,2),                 -- PRECO_CUSTO (reposição) no momento
  classe             TEXT,                          -- GERAL | PB | EXCLUSIVO | OPORTUNIDADE
  mix                INTEGER,
  faixa              TEXT,                          -- 1A..3D
  markup_regua       NUMERIC(6,3),
  desc_max_pct       NUMERIC(6,4),
  preco_minimo       NUMERIC(15,2),
  acima_alcada       BOOLEAN NOT NULL DEFAULT FALSE,
  estoque_disponivel NUMERIC(15,3),                 -- fotografia do saldo na hora
  substituto_de      INTEGER,                       -- pro_codigo sem saldo que este item substitui
  observacao         TEXT
);
-- Item em promoção vigente na tabela do cliente (preço fechado; define a validade).
ALTER TABLE ven_orcamento_item ADD COLUMN IF NOT EXISTS promocao_codigo INTEGER;
ALTER TABLE ven_orcamento_item ADD COLUMN IF NOT EXISTS promocao_fim    DATE;
CREATE INDEX IF NOT EXISTS idx_ven_orcamento_item_orc ON ven_orcamento_item (orcamento_id);
CREATE INDEX IF NOT EXISTS idx_ven_orcamento_item_pro ON ven_orcamento_item (pro_codigo);

-- 5) Vendem juntos (apuração semanal no BI) -------------------------------------
CREATE TABLE IF NOT EXISTS ven_produto_relacionado (
  pro_codigo       INTEGER NOT NULL,
  pro_relacionado  INTEGER NOT NULL,
  juntos           INTEGER NOT NULL,                -- notas em que os dois saíram juntos
  base             INTEGER NOT NULL,                -- notas em que pro_codigo saiu
  suporte_pct      NUMERIC(6,4) NOT NULL,           -- juntos / base
  calculado_em     TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (pro_codigo, pro_relacionado)
);

-- 5b) Vendem juntos por SUBGRUPO. No atacado a maioria dos produtos sai em
--     poucas notas e não forma par próprio (>= 3 notas juntos); o que sai junto
--     com QUALQUER item do subgrupo (cola, arame de remoção com para-brisa)
--     tem base de milhares de notas e cobre esses itens.
CREATE TABLE IF NOT EXISTS ven_subgrupo_relacionado (
  subgrp_codigo    INTEGER NOT NULL,
  pro_relacionado  INTEGER NOT NULL,                -- produto de OUTRO subgrupo
  juntos           INTEGER NOT NULL,                -- notas com o subgrupo e o produto
  base             INTEGER NOT NULL,                -- notas em que o subgrupo saiu
  suporte_pct      NUMERIC(6,4) NOT NULL,           -- juntos / base
  calculado_em     TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (subgrp_codigo, pro_relacionado)
);

-- 6) Permissão da tela (módulo Vendas é ESTRITO: cada tela liberada por usuário).
-- Exemplo — ajuste os usuários:
-- INSERT INTO sis_permissoes (id, usuario_id, modulo, tela, visualizar, editar, criar, deletar)
-- SELECT gen_random_uuid()::text, u.id, 'Vendas', '/vendas/orcamento', true, true, true, false
-- FROM sis_usuarios u WHERE u.codigo IN ('<codigo>') AND NOT EXISTS (
--   SELECT 1 FROM sis_permissoes p WHERE p.usuario_id = u.id AND p.tela = '/vendas/orcamento');

-- 7) Entrega ao cliente (Estação do WhatsApp, 03/09/2026): quando e por onde o
--    orçamento foi ENTREGUE ao cliente (mensagem + PDF pelo WhatsApp do vendedor).
--    `enviado_em` continua sendo o momento em que o vendedor fechou a proposta.
ALTER TABLE ven_orcamento ADD COLUMN IF NOT EXISTS entregue_canal TEXT;
ALTER TABLE ven_orcamento ADD COLUMN IF NOT EXISTS entregue_em    TIMESTAMPTZ;

-- 8) Pagamento (16/09/2026): o Celta exige condição (CONDICOES_PAGTO.CP_CODIGO) e
--    forma (FORMAS_PAGTO.FP_CODIGO) no orçamento. A forma escolhida vale para a
--    entrada e para as demais parcelas. As descrições são cópia do ERP na hora
--    de salvar, para o PDF e a mensagem não dependerem de nova consulta.
ALTER TABLE ven_orcamento ADD COLUMN IF NOT EXISTS cp_codigo    INTEGER;
ALTER TABLE ven_orcamento ADD COLUMN IF NOT EXISTS cp_descricao TEXT;
ALTER TABLE ven_orcamento ADD COLUMN IF NOT EXISTS fp_codigo    TEXT;
ALTER TABLE ven_orcamento ADD COLUMN IF NOT EXISTS fp_descricao TEXT;

-- 9) Venda perdida com similar em estoque (16/09/2026): quando o item sem saldo
--    tinha um equivalente com saldo, o vendedor precisa justificar por escrito
--    para registrar a venda perdida. `similar_disponivel` guarda qual era.
ALTER TABLE ven_venda_perdida ADD COLUMN IF NOT EXISTS similar_disponivel TEXT;
ALTER TABLE ven_venda_perdida ADD COLUMN IF NOT EXISTS justificativa      TEXT;

-- 8) Itens sem saldo ao concluir (16/09/2026). Ao enviar, o saldo é relido do
--    ERP; item com saldo menor que o pedido exige decisão do vendedor:
--    venda perdida (registro abaixo), encomenda (parte fica no orçamento marcada
--    como `qtd_encomenda`, entrega depois) ou só retirar. A análise de estoque
--    lê `ven_venda_perdida` junto da VENDA_PERDIDA do ERP.
ALTER TABLE ven_orcamento_item ADD COLUMN IF NOT EXISTS qtd_encomenda NUMERIC(15,3) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS ven_venda_perdida (
  id                TEXT PRIMARY KEY,
  orcamento_id      TEXT NOT NULL REFERENCES ven_orcamento(id) ON DELETE CASCADE,
  orcamento_numero  INTEGER,
  pro_codigo        INTEGER NOT NULL,
  descricao         TEXT,
  quantidade        NUMERIC(15,3) NOT NULL,
  cli_codigo        INTEGER,
  rep_codigo        INTEGER,
  motivo            TEXT NOT NULL DEFAULT 'SEM_SALDO',
  usuario_id        TEXT,
  usuario_nome      TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_ven_venda_perdida_orc_pro UNIQUE (orcamento_id, pro_codigo)  -- uma vez por item e orçamento
);
CREATE INDEX IF NOT EXISTS idx_ven_venda_perdida_pro ON ven_venda_perdida (pro_codigo);

-- 9) Vender fora da promoção/liquidação (16/09/2026): o vendedor escolhe vender
--    o item pela tabela normal do cliente; a campanha deixa de valer na linha e
--    entram a régua e a bolsa padrão.
ALTER TABLE ven_orcamento_item ADD COLUMN IF NOT EXISTS fora_promocao BOOLEAN NOT NULL DEFAULT FALSE;

-- 10) Importação no Celta (16/09/2026): ao fechar, o vendedor pode mandar o orçamento
--     ao ERP pela api-vendas-service. O nº gerado vai na coluna "orcamentoCelta"
--     (já existia no banco, nome com maiúscula — o Prisma mapeia como celta_orcamento);
--     FECHADO sem nº = "não importado" (a tela oferece importar depois).
ALTER TABLE ven_orcamento ADD COLUMN IF NOT EXISTS "orcamentoCelta"    INTEGER;
ALTER TABLE ven_orcamento ADD COLUMN IF NOT EXISTS celta_importado_em TIMESTAMPTZ;

-- 11) Acréscimo (19/09/2026): o vendedor pode cobrar o item acima da tabela. O desconto
--     da linha fica zero e a diferença (preço cobrado − tabela) × quantidade, em R$, é
--     gravada aqui. Campo só de banco/relatório: nenhuma tela, PDF ou o Celta o exibe.
ALTER TABLE ven_orcamento_item ADD COLUMN IF NOT EXISTS acrescimo NUMERIC(15,2) NOT NULL DEFAULT 0;

-- 12) ICMS na venda para fora do estado (24/09/2026): o orçamento mostra o imposto como a
--     nota vai sair. Cliente contribuinte de outro estado (indicador de IE 1): ICMS-ST por
--     item. Cliente não contribuinte/isento (9/2), venda não presencial: DIFAL por item, cobrado do
--     cliente como despesa acessória (acordo com os clientes do atacado). Os dois somam ao total
--     apresentado ao cliente (`total` continua sendo só a mercadoria; total ao cliente = total +
--     icms_st + difal); bolsa e margem não mudam (repasse).
--     `tributacao` guarda o regime aplicado (NENHUM | ST | DIFAL | PRESENCIAL | FORA_ESCOPO);
--     `presencial` é o mesmo indicador de presença da NF-e (padrão não presencial no atacado).
--     `difal_pct` NULL num item com regime DIFAL = produto sem alíquota cadastrada no Celta.
ALTER TABLE ven_orcamento ADD COLUMN IF NOT EXISTS presencial BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ven_orcamento ADD COLUMN IF NOT EXISTS tributacao TEXT;
ALTER TABLE ven_orcamento ADD COLUMN IF NOT EXISTS icms_st    NUMERIC(15,2) NOT NULL DEFAULT 0;
ALTER TABLE ven_orcamento ADD COLUMN IF NOT EXISTS difal      NUMERIC(15,2) NOT NULL DEFAULT 0;
ALTER TABLE ven_orcamento_item ADD COLUMN IF NOT EXISTS icms_st   NUMERIC(15,2) NOT NULL DEFAULT 0;
ALTER TABLE ven_orcamento_item ADD COLUMN IF NOT EXISTS difal     NUMERIC(15,2) NOT NULL DEFAULT 0;
ALTER TABLE ven_orcamento_item ADD COLUMN IF NOT EXISTS difal_pct NUMERIC(6,4);

-- 13) Meia nota (24/09/2026): venda que sai metade em produto e metade em serviço. Só muda a
--     estimativa do imposto interestadual no orçamento: ST e DIFAL calculados sobre metade do
--     valor de cada item, e na importação ao Celta o valor vai em "Desp. Acessórias" em vez das
--     colunas de tributação. Estimativa comercial do que o cliente paga; a nota é do Celta.
ALTER TABLE ven_orcamento ADD COLUMN IF NOT EXISTS meia_nota BOOLEAN NOT NULL DEFAULT FALSE;

-- 14) Compra de oportunidade (25/09/2026): reserva da empresa na bolsa do vendedor. A gestão
--     registra a nota de compra e o % da sobra (tabela − custo × piso) que fica com o vendedor;
--     grava-se por produto o CUSTO PARA A BOLSA (fixo em R$) que a bolsa usa no lugar do custo
--     real enquanto o lote durar. Um registro por lote: registrar de novo encerra o anterior.
--     Encerra sozinho quando as unidades vendidas desde o registro chegam à quantidade.
CREATE TABLE IF NOT EXISTS ven_bolsa_oportunidade (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pro_codigo    INTEGER NOT NULL,
  descricao     TEXT,
  nfe           INTEGER,                          -- NF_ENTRADA.NFE (empresa 1)
  nota_fiscal   INTEGER,
  for_codigo    INTEGER,
  for_nome      TEXT,
  quantidade    NUMERIC(15,4) NOT NULL,           -- unidades do lote cobertas pela regra
  custo_nota    NUMERIC(15,4),                    -- custo do item na nota (informação)
  custo         NUMERIC(15,4) NOT NULL,           -- custo de reposição no dia do registro
  preco_tabela  NUMERIC(15,2) NOT NULL,           -- PRECO2 no dia do registro
  piso          NUMERIC(8,4)  NOT NULL,           -- piso da bolsa no dia do registro
  pct_vendedor  NUMERIC(5,4)  NOT NULL,           -- fração da sobra que fica com o vendedor
  custo_bolsa   NUMERIC(15,4) NOT NULL,           -- custo que a bolsa usa (fixo em R$)
  vigente_de    DATE NOT NULL,                    -- vendas a partir deste dia
  vendida       NUMERIC(15,4) NOT NULL DEFAULT 0, -- apurada no BI (todos os canais, devolução desconta)
  apurado_em    TIMESTAMPTZ,
  encerrado_em  DATE,                             -- vendas a partir deste dia voltam ao custo real
  criado_por    TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ven_bolsa_oportunidade_pro_idx ON ven_bolsa_oportunidade (pro_codigo);

-- 15) Venda perdida pela pesquisa de produtos (26/09/2026): o vendedor aperta F7 no item sem saldo
--     e registra a perda sem pôr o item no orçamento. O registro nasce sem orçamento (cliente,
--     vendedor, produto, quantidade 1, motivo SEM_SALDO, similar/justificativa); se o mesmo item
--     cair como venda perdida no Fechou do dia, o serviço amarra este registro ao orçamento em vez
--     de criar outro. Sem orçamento vale UM por cliente + produto + dia (dia de Cuiabá).
ALTER TABLE ven_venda_perdida ALTER COLUMN orcamento_id DROP NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_ven_venda_perdida_pesquisa_dia
  ON ven_venda_perdida (cli_codigo, pro_codigo, ((created_at AT TIME ZONE 'America/Cuiaba')::date))
  WHERE orcamento_id IS NULL;
